<a href="https://colab.research.google.com/github/hafizzx/python-projects/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv("/content/students_150_multiple_features.csv")

df.head()

,CGPA,IQ_Level,Field_Interest,Programming_Skill,Communication_Skill,Salary_Package_PKR
0,2.75,117.0,1.0,2.0,9.0,319694.0
1,3.90,85.0,5.0,3.0,2.0,344377.0
2,3.46,103.0,6.0,1.0,9.0,335458.0
3,3.20,86.0,3.0,1.0,1.0,266603.0
4,2.31,137.0,9.0,3.0,1.0,317019.0


In [4]:
df.shape

(150, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   CGPA                 149 non-null    float64
 1   IQ_Level             149 non-null    float64
 2   Field_Interest       149 non-null    float64
 3   Programming_Skill    149 non-null    float64
 4   Communication_Skill  149 non-null    float64
 5   Salary_Package_PKR   149 non-null    float64
dtypes: float64(6)
memory usage: 7.2 KB


In [6]:
df.describe()

,CGPA,IQ_Level,Field_Interest,Programming_Skill,Communication_Skill,Salary_Package_PKR
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,2.940403,112.302013,5.724832,5.510067,5.161074,376430.530201
std,0.591672,16.219651,2.983873,2.990113,2.924886,69424.453617
min,2.010000,85.000000,1.000000,1.000000,1.000000,184787.000000
25%,2.420000,100.000000,3.000000,3.000000,2.000000,329775.000000
50%,2.880000,113.000000,6.000000,5.000000,5.000000,374691.000000
75%,3.460000,124.000000,8.000000,8.000000,8.000000,430449.000000
max,3.970000,140.000000,10.000000,10.000000,10.000000,500000.000000


In [7]:
df.isnull().sum()

,0
CGPA,1
IQ_Level,1
Field_Interest,1
Programming_Skill,1
Communication_Skill,1
Salary_Package_PKR,1


In [8]:
df = df.fillna(df.mean(numeric_only=True))

In [9]:
df.isnull().sum()

,0
CGPA,0
IQ_Level,0
Field_Interest,0
Programming_Skill,0
Communication_Skill,0
Salary_Package_PKR,0


In [10]:
fig = px.scatter(
    df,
    x="CGPA",
    y="Salary_Package_PKR",
    title="CGPA vs Salary",
    trendline="ols"
)

fig.show()

In [11]:
fig = px.scatter(
    df,
    x="IQ_Level",
    y="Salary_Package_PKR",
    title="IQ Level vs Salary",
    trendline="ols"
)

fig.show()

In [12]:
fig = px.scatter(
    df,
    x="Communication_Skill",
    y="Salary_Package_PKR",
    title="Communication Skill vs Salary",
    trendline="ols"
)

fig.show()

In [13]:
features = [
    "CGPA",
    "IQ_Level",
    "Field_Interest",
    "Programming_Skill",
    "Communication_Skill"
]

X = df[features].values

y = df["Salary_Package_PKR"].values

In [14]:
X

array([[  2.75      , 117.        ,   1.        ,   2.        ,
          9.        ],
       [  3.9       ,  85.        ,   5.        ,   3.        ,
          2.        ],
       [  3.46      , 103.        ,   6.        ,   1.        ,
          9.        ],
       [  3.2       ,  86.        ,   3.        ,   1.        ,
          1.        ],
       [  2.31      , 137.        ,   9.        ,   3.        ,
          1.        ],
       [  2.31      , 128.        ,   5.        ,   5.        ,
          5.        ],
       [  2.12      , 110.        ,   8.        ,   3.        ,
          6.        ],
       [  2.94040268, 116.        ,   1.        ,   1.        ,
          6.        ],
       [  3.2       ,  90.        ,   5.        ,   1.        ,
          3.        ],
       [  3.42      , 116.        ,   3.        ,   8.        ,
          7.        ],
       [  2.04      , 139.        ,   1.        ,  10.        ,
          9.        ],
       [  3.94      ,  88.        ,   4.   

In [15]:
y

array([319694.        , 344377.        , 335458.        , 266603.        ,
       317019.        , 362733.        , 311304.        , 330881.        ,
       332073.        , 482741.        , 403051.        , 377221.        ,
       416233.        , 278733.        , 296969.        , 312360.        ,
       343706.        , 487069.        , 373949.        , 465842.        ,
       500000.        , 374691.        , 320792.        , 333525.        ,
       444818.        , 390691.        , 388518.        , 356112.        ,
       433805.        , 184787.        , 468996.        , 258677.        ,
       333556.        , 353523.        , 479142.        , 367981.        ,
       398098.        , 345724.        , 382187.        , 479967.        ,
       265655.        , 236633.        , 364777.        , 412509.        ,
       439533.        , 319200.        , 406239.        , 416574.        ,
       371386.        , 292853.        , 359323.        , 404603.        ,
       500000.        , 4

In [16]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (150, 5)
y shape: (150,)


In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (120, 5)
Testing: (30, 5)


In [21]:
model = LinearRegression()

In [22]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_test

array([430449.        , 373949.        , 324173.        , 352248.        ,
       414506.        , 258677.        , 335759.        , 430556.        ,
       274230.        , 364525.        , 333055.        , 416233.        ,
       398098.        , 482741.        , 465842.        , 279214.        ,
       424349.        , 431564.        , 411450.        , 376430.53020134,
       184787.        , 422776.        , 388518.        , 417852.        ,
       316767.        , 387183.        , 337909.        , 329362.        ,
       319200.        , 468996.        ])

In [29]:
y_pred = model.predict(X_test)

In [30]:
y_pred

array([426853.06500439, 401445.38954033, 397729.89552887, 353098.5719638 ,
       388246.48880873, 260331.72000014, 341023.10781643, 427245.31576836,
       293197.53642674, 318375.82803668, 324115.16112147, 424593.55331513,
       397721.36584467, 431618.92093198, 469792.9279927 , 265641.49065706,
       422349.6582033 , 418988.56578481, 445794.06724375, 317903.34323045,
       215916.1789671 , 377609.52767584, 345460.60851411, 401542.86683886,
       329944.44916371, 336091.65943403, 298444.43575474, 345098.23695594,
       326624.81355687, 449721.07279389])

In [31]:
mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 909193631.7624493


In [32]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error

model = SGDRegressor(
    max_iter=1000,
    learning_rate="constant",
    eta0=0.01,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Weights:", model.coef_)
print("Bias:", model.intercept_)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

Weights: [ 1.68549760e+11  9.32632567e+10  7.51168490e+11 -1.60273642e+11
 -6.58744276e+10]
Bias: [2.2585523e+10]
MSE: 2.0609580124431882e+26
